language: php

sudo: false

php:
  - 5.6
  - 7.2

before_script:
  - composer install

script: ./vendor/bin/phpunit --configuration phpunit.xml --verbose --coverage-text

notifications:
  email: false
