<?php

namespace Zumba\CodingStandards;

class ExtraTokens {

	public static $docCommentTokens = [
		T_DOC_COMMENT            => T_DOC_COMMENT,
		T_DOC_COMMENT_STAR       => T_DOC_COMMENT_STAR,
		T_DOC_COMMENT_WHITESPACE => T_DOC_COMMENT_WHITESPACE,
		T_DOC_COMMENT_TAG        => T_DOC_COMMENT_TAG,
		T_DOC_COMMENT_OPEN_TAG   => T_DOC_COMMENT_OPEN_TAG,
		T_DOC_COMMENT_CLOSE_TAG  => T_DOC_COMMENT_CLOSE_TAG,
		T_DOC_COMMENT_STRING     => T_DOC_COMMENT_STRING,
	];

}
